/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ShowIdRouteImport } from './routes/show.$id'
import { Route as ShowIdSeasonNRouteImport } from './routes/show.$id.season.$n'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShowIdRoute = ShowIdRouteImport.update({
  id: '/show/$id',
  path: '/show/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ShowIdSeasonNRoute = ShowIdSeasonNRouteImport.update({
  id: '/season/$n',
  path: '/season/$n',
  getParentRoute: () => ShowIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/show/$id': typeof ShowIdRouteWithChildren
  '/show/$id/season/$n': typeof ShowIdSeasonNRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/show/$id': typeof ShowIdRouteWithChildren
  '/show/$id/season/$n': typeof ShowIdSeasonNRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/show/$id': typeof ShowIdRouteWithChildren
  '/show/$id/season/$n': typeof ShowIdSeasonNRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/auth' | '/show/$id' | '/show/$id/season/$n'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/auth' | '/show/$id' | '/show/$id/season/$n'
  id: '__root__' | '/' | '/auth' | '/show/$id' | '/show/$id/season/$n'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  ShowIdRoute: typeof ShowIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/show/$id': {
      id: '/show/$id'
      path: '/show/$id'
      fullPath: '/show/$id'
      preLoaderRoute: typeof ShowIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/show/$id/season/$n': {
      id: '/show/$id/season/$n'
      path: '/season/$n'
      fullPath: '/show/$id/season/$n'
      preLoaderRoute: typeof ShowIdSeasonNRouteImport
      parentRoute: typeof ShowIdRoute
    }
  }
}

interface ShowIdRouteChildren {
  ShowIdSeasonNRoute: typeof ShowIdSeasonNRoute
}

const ShowIdRouteChildren: ShowIdRouteChildren = {
  ShowIdSeasonNRoute: ShowIdSeasonNRoute,
}

const ShowIdRouteWithChildren =
  ShowIdRoute._addFileChildren(ShowIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  ShowIdRoute: ShowIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
