/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProfileUsernameRouteImport } from './routes/profile.$username'
import { Route as ShowIdIndexRouteImport } from './routes/show.$id.index'
import { Route as ShowIdSeasonNRouteImport } from './routes/show.$id.season.$n'
import { Route as ShowIdSeasonNEpisodeERouteImport } from './routes/show.$id.season.$n.episode.$e'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileUsernameRoute = ProfileUsernameRouteImport.update({
  id: '/profile/$username',
  path: '/profile/$username',
  getParentRoute: () => rootRouteImport,
} as any)
const ShowIdIndexRoute = ShowIdIndexRouteImport.update({
  id: '/show/$id/',
  path: '/show/$id/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShowIdSeasonNRoute = ShowIdSeasonNRouteImport.update({
  id: '/show/$id/season/$n',
  path: '/show/$id/season/$n',
  getParentRoute: () => rootRouteImport,
} as any)
const ShowIdSeasonNEpisodeERoute = ShowIdSeasonNEpisodeERouteImport.update({
  id: '/episode/$e',
  path: '/episode/$e',
  getParentRoute: () => ShowIdSeasonNRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/profile/$username': typeof ProfileUsernameRoute
  '/show/$id/': typeof ShowIdIndexRoute
  '/show/$id/season/$n': typeof ShowIdSeasonNRouteWithChildren
  '/show/$id/season/$n/episode/$e': typeof ShowIdSeasonNEpisodeERoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/profile/$username': typeof ProfileUsernameRoute
  '/show/$id': typeof ShowIdIndexRoute
  '/show/$id/season/$n': typeof ShowIdSeasonNRouteWithChildren
  '/show/$id/season/$n/episode/$e': typeof ShowIdSeasonNEpisodeERoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/profile/$username': typeof ProfileUsernameRoute
  '/show/$id/': typeof ShowIdIndexRoute
  '/show/$id/season/$n': typeof ShowIdSeasonNRouteWithChildren
  '/show/$id/season/$n/episode/$e': typeof ShowIdSeasonNEpisodeERoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/profile/$username'
    | '/show/$id/'
    | '/show/$id/season/$n'
    | '/show/$id/season/$n/episode/$e'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/profile/$username'
    | '/show/$id'
    | '/show/$id/season/$n'
    | '/show/$id/season/$n/episode/$e'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/profile/$username'
    | '/show/$id/'
    | '/show/$id/season/$n'
    | '/show/$id/season/$n/episode/$e'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  ProfileUsernameRoute: typeof ProfileUsernameRoute
  ShowIdIndexRoute: typeof ShowIdIndexRoute
  ShowIdSeasonNRoute: typeof ShowIdSeasonNRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/$username': {
      id: '/profile/$username'
      path: '/profile/$username'
      fullPath: '/profile/$username'
      preLoaderRoute: typeof ProfileUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/show/$id/': {
      id: '/show/$id/'
      path: '/show/$id'
      fullPath: '/show/$id/'
      preLoaderRoute: typeof ShowIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/show/$id/season/$n': {
      id: '/show/$id/season/$n'
      path: '/show/$id/season/$n'
      fullPath: '/show/$id/season/$n'
      preLoaderRoute: typeof ShowIdSeasonNRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/show/$id/season/$n/episode/$e': {
      id: '/show/$id/season/$n/episode/$e'
      path: '/episode/$e'
      fullPath: '/show/$id/season/$n/episode/$e'
      preLoaderRoute: typeof ShowIdSeasonNEpisodeERouteImport
      parentRoute: typeof ShowIdSeasonNRoute
    }
  }
}

interface ShowIdSeasonNRouteChildren {
  ShowIdSeasonNEpisodeERoute: typeof ShowIdSeasonNEpisodeERoute
}

const ShowIdSeasonNRouteChildren: ShowIdSeasonNRouteChildren = {
  ShowIdSeasonNEpisodeERoute: ShowIdSeasonNEpisodeERoute,
}

const ShowIdSeasonNRouteWithChildren = ShowIdSeasonNRoute._addFileChildren(
  ShowIdSeasonNRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  ProfileUsernameRoute: ProfileUsernameRoute,
  ShowIdIndexRoute: ShowIdIndexRoute,
  ShowIdSeasonNRoute: ShowIdSeasonNRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
